#!/usr/bin/env python
"""Simple Mandelbrot Set plotter for the terminal, done in Textual."""

######################################################################
# Main app information.
__author__     = "Dave Pearson"
__copyright__  = "Copyright 2022, Dave Pearson"
__credits__    = [ "Dave Pearson" ]
__maintainer__ = "Dave Pearson"
__email__      = "davep@davep.org"
__version__    = "0.0.1"
__licence__    = "GPLv3+"

##############################################################################
# Python imports.
from decimal  import Decimal
from typing   import Iterator, Final
from operator import mul, truediv

##############################################################################
# Textual imports.
from textual.app      import App, ComposeResult
from textual.binding  import Binding
from textual.widgets  import Static, Header, Footer
from textual.reactive import reactive

##############################################################################
class MandelPoint( Static ):
    """Widget that handles drawing a specific point in the set."""

    MAX_ITERATION: Final = 80
    """Maximum number of iterations to calculate to."""

    result = reactive( 0 )
    """int: The result of calculating this point in the Mandelbrot set."""

    @staticmethod
    def at( x: int, y: int ) -> str:
        """Get the ID of a Mandelbrot point at a given position.

        Args:
            x (int): The X location of the cell.
            y (int): The Y location of the cell.

        Returns:
            str: The ID for the cell.
        """
        return f"point-{x}-{y}"

    @classmethod
    def mandelbrot( cls, x: Decimal, y: Decimal ) -> int:
        """Return the Mandelbrot calculation for the point.

        Returns:
            int: The number of loops to escape, or 0 if it didn't.

        Note:
            The point is considered to be stable, considered to have not
            escaped, if the ``max_iteration`` has been hit without the
            calculation going above 2.0.
        """
        c1 = complex( x, y )
        c2 = 0j
        for n in range( cls.MAX_ITERATION ):
            if abs( c2 ) > 2:
                return n
            c2 = c1 + ( c2 * c2 )
        return 0

    def __init__( self, x: Decimal, y: Decimal ) -> None:
        """Initialise a point in the Mandelbrot Set.

        Args:
            x (Decimal): The X position of the point in the set.
            y (Decimal): The Y position of the point in the set.
        """
        super().__init__()
        self.add_class( "no-text" )
        self.calc( x, y )

    def calc( self, x: Decimal, y: Decimal ) -> None:
        """Perform the Mandelbrot calculation for this point in the set."""
        self.result = self.mandelbrot( x, y )

    def watch_result( self, new_result: int ) -> None:
        """React to the Point changing.

        Args:
            new_point (Point): The new value for the point.
        """
        # Point has moved so let's remove any class that isn't the one that
        # controls if the calculation result of the point is shown...
        self.remove_class( *filter( lambda c: c!= "no-text", self.classes ) )
        # ...and then calculate the classes again.
        self.add_class( f"escape-{min( int( new_result ), 15 )}" )
        # Finally update the content with the new result.
        self.update( str( new_result ) )

##############################################################################
class MandelbrotPlot( App[ None ] ):
    """An app to plot a Mandelbrot Set in the terminal."""

    TITLE = "trMandelbrot -- A Terminal Mandelbrot Set Plotter"
    """str: The title of the application."""

    CSS_PATH = "mandelplot.css"
    """str: The name of the CSS file."""

    SIZE = 40
    """int: The width/height of the plot."""

    BINDINGS = [
        Binding( "up", "move( -0.1, 0 )", "Up", key_display="↑" ),
        Binding( "down", "move( 0.1, 0 )", "Down", key_display="↓" ),
        Binding( "left", "move( 0, -0.1 )", "Left", key_display="←" ),
        Binding( "right", "move( 0, 0.1 )", "Right", key_display="→" ),
        Binding( "right_square_bracket", "zoom( -1.2 )", "In", key_display="]" ),
        Binding( "left_square_bracket", "zoom( 1.2 )", "Out", key_display="[" ),
        Binding( "right_curly_bracket", "zoom( -2.0 )", "In+", key_display="}" ),
        Binding( "left_curly_bracket", "zoom( 2.0 )", "Out+", key_display="{" ),
        ( "e", "toggle_escape", "Toggle #s" ),
        ( "q", "quit", "Quit" ),
        ( "r", "remove", "Remove Test" )
    ]
    """The keyboard bindings for the app."""

    from_x = reactive( Decimal( -2.0 ) )
    to_x   = reactive( Decimal( 2.0 ) )
    from_y = reactive( Decimal( -2.5 ) )
    to_y   = reactive( Decimal( 1.5 ) )

    canvas: dict[ str, MandelPoint ] = {}

    def refresh_title( self ) -> None:
        """Refresh the title to show the dimensions."""
        self.title = f"{self.TITLE} -- ({self.from_x:.2f}, {self.from_y:.2f} -> {self.to_x:.2f}, {self.to_y:.2f})"

    def on_mount( self ) -> None:
        """Do some stuff once the DOM is loaded."""
        self.refresh_title()

    def watch_from_x( self, _ ):
        """React to ``from_x`` being modified."""
        self.refresh_title()

    def watch_from_y( self, _ ):
        """React to ``from_y`` being modified."""
        self.refresh_title()

    @classmethod
    def frange( cls, r_from: Decimal, r_to: Decimal ) -> Iterator[ Decimal ]:
        """Generate a float range for the plot.

        Args:
            r_from (Decimal): The value to generate from.
            r_to (Decimal): The value to generate to.

        Yields:
            Decimal: Values between the range to fit the plot.
        """
        steps = 0
        step  = Decimal( r_to - r_from ) / Decimal( cls.SIZE )
        n     = Decimal( r_from )
        while n < r_to and steps < cls.SIZE:
            yield n
            n += Decimal( step )
            steps += 1

    def compose( self ) -> ComposeResult:
        """Compose the main screen..

        Returns:
            ComposeResult: The result of composing the screen.
        """
        yield Header()
        for col, x in enumerate( self.frange( self.from_x, self.to_x ) ):
            for row, y in enumerate( self.frange( self.from_y, self.to_y ) ):
                yield ( point := MandelPoint( y, x ) )
                self.canvas[ MandelPoint.at( col, row ) ] = point
        yield Footer()

    def action_toggle_escape( self ) -> None:
        """Toggle the display of the escape values for each cell."""
        self.query( MandelPoint ).toggle_class( "no-text" )

    def action_remove( self ) -> None:
        """Perform a worst-case remove.

        Note: This doesn't do anything useful at all, it just tests a
        worst-case don't-ever-do-this thing in Textual itself. Handy for
        performance testing.
        """
        self.query( MandelPoint ).remove()

    def repaint_canvas( self ) -> None:
        """Repaint the Mandelbrot canvas."""
        for col, x in enumerate( self.frange( self.from_x, self.to_x ) ):
            for row, y in enumerate( self.frange( self.from_y, self.to_y ) ):
                self.canvas[ f"{MandelPoint.at( col, row )}" ].calc( y, x )

    def action_move( self, x: Decimal, y: Decimal ) -> None:
        """Move the Mandelbrot Set within the view.

        Args:
            x (Decimal): The amount to move in the X direction.
            y (Decimal): The amount to move in the Y direction.
        """
        self.from_x += Decimal( x )
        self.to_x   += Decimal( x )
        self.from_y += Decimal( y )
        self.to_y   += Decimal( y )
        self.repaint_canvas()

    def action_zoom( self, zoom: Decimal ):
        """Zoom in our out.

        Args:
            zoom (Decimal): The amount to zoom by.
        """

        # Figure the operator from the sign.
        by = truediv if zoom < 0 else mul

        # We don't need the sign anymore.
        zoom = Decimal( abs( zoom ) )

        # Apply the zoom.
        self.from_x = Decimal( by( self.from_x, zoom ) )
        self.to_x   = Decimal( by( self.to_x,   zoom ) )
        self.from_y = Decimal( by( self.from_y, zoom ) )
        self.to_y   = Decimal( by( self.to_y,   zoom ) )

        # Repaint.
        self.repaint_canvas()

##############################################################################
# Main code.
if __name__  == "__main__":
    MandelbrotPlot().run()

### mandelplot.py ends here
